name: action-project
on: push
jobs:
    
    build:
      runs-on: ubuntu-latest
      defaults:
        run: 
            working-directory: using-action/react-app
      steps:
        #checkout the code from the repo
        - name: checkout code
          uses: actions/checkout@v4
        - name: Printing folders
          run: ls
        - name: Setup-node
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
    #install the dependency of our react
        - name: Install Dependecies
          run: npm ci  
          # execute automated test 
        - name: Run unit test
          run: npm run test
          