name: concurency-1
on:
    workflow_dispatch: 
        inputs:
            environment:
                type: environment
                description: "Environment"
                required: true
concurrency: 
    group: concurency-1
    cancel-in-progress: true
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30