name: with environmets
on:
    
    workflow_dispatch: 
        inputs:
            target-env:
                default: "staging"
                required: true
                type: environment
jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{inputs.target-env}}
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value'}}

        steps:
            - name: "echo vars"
              run: |
                echo env variable is having a value: ${{env.my-env-value}}



