name: Repo Events
on: 
    push:
    pull_request:
        types: [opened,assigned,reopened,synchronize]
    issues:
        types: [opened]
jobs:
  chekout-lab-events:
    runs-on: ubuntu-latest
    steps:
     - run: |
         echo $GITHUB_SHA
         echo $GITHUB_REF
     - uses: actions/checkout@v3