name: using expression
on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
              description: "Enabling Debugging mode"
              type: boolean
              default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print Start-up-data'
              if: ${{inputs.debug==true}}
              run: |
                 echo "Triggered by:${{github.event_name}}"
                 echo "Branch:${{github.ref}}"
                 echo "Commit:${{github.sha}}"
                 echo "Runner OS:${{runner.os}}"
            - name: '[debug] Print when triggered from Mian'
              if: ${{inputs.debug == true  && github.ref == 'refs/heads/main'}}
              run: echo "I triggered from main"
            - name: Hello
              run: echo "Hello world from Me!!"

            
     
