name: Firstflow
on: [push]
jobs:
  run-shell-commands:
   runs-on: ubuntu-latest
   steps:
    - name: echo a string
      run: echo "Hello world"
    - name: Multiline command 
      run: |
        node -version
        npm -version
  #Run Parallel Job      
  parallel-job-macos:
    runs-on: macos-latest
    needs: run-shell-commands
    steps:
      - name: View SW Version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs:  run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      - name: error step
        run: Write-Outputs "Windows String fixed"

      