name: Handling failed jobs in Matrix
on:
    push:
jobs:
    matrix-node:
        continue-on-error: false
        strategy:
            matrix:
                os: [ubuntu-latest,windows-latest]
                node-vs: [14,15,16]
                include:
                    - os: ubuntu-latest
                      is-ubuntu: true
                    - os: ubuntu-latest
                      node-js-vs: 16
                      experimental: true  
                    - os: ubuntu-latest
                      node-js-vs: 17
            fail-fast: false      
        runs-on: ${{matrix.os}}                  
        steps:
          - if: matrix.experimental==true
            run: exit 1
          - run: node -v
          - run: echo '${{toJson(matrix)}}'
          - uses: actions/setup-node@v3
            with:
                node-version: ${{matrix.node-vs}}
          - run: node -v         
              
