name: Matrix-example-1
on:
    push:
jobs:
    node-js-check:
        continue-on-error: false

        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [winows-latest,ubuntu-latest]
                node-js-vs: [14, 15, 16]
                include:
                  - os: ubuntu-latest
                    is-ubuntu: true 
                  - os: macos-latest
                    node-js-vs: 15
                  - experimental: false    
                  - os: ubuntu-latest
                    node-js-vs: 16
                    experimental: true    
                 
        steps:
            - name: echo matrix
              run: echo ${{toJson(matrix)}}
            - name: Setup-node
              run: node -v
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{matrix.node-js-vs}}
            - name: Verify Node.js version
              run: node -v
