name: Matrix-example-1
on:
    push:
jobs:
    node-js-check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [winows-latest,ubuntu-latest]
                node-js-vs: [12, 14, 16]
                include:
                  - os: ubuntu-latest
                    is-ubuntu: true  
                 
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Setup-node
              run: node -v
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{matrix.node-js-vs}}
            - name: Verify Node.js version
              run: node -v
