name: Working-with-matrix
on:
    push:
jobs:
    
    backward-compatibility:
        runs-on: ubuntu-latest
        strategy:
            matrix:
             fruit: [apple, pear]
             animal: [cat, dog]
             include:
                   - color: green 
        steps:
            - name: Eho
              run: echo ${{matrix.fruit}}-${{matrix.animal}}