name: Reusable-workflow-output
on:
    workflow_call: 
        outputs:
            date:
                description: "Date Value"
                value: ${{jobs.generate-output.outputs.date}}
jobs:
    generate-output:
        outputs:
            date: ${{steps.dateprint.outputs.date}}
        runs-on: ubuntu-latest
        steps:
            - run: echo "date=$(date)">>"$GITHUB_OUTPUT"
              id: dateprint