name: working directiory and Shells
on: [push]
defaults:
  run:
    shell: bash
    #working-directory: /dev/abc
jobs:
  display-working-directory:
    runs-on: ubuntu-latest
    steps: 
     - name: Displays working directory and List of files
       run: |
         pwd
         ls -a
         echo $GITHUB_SHA             
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
     # setting up in windows
  display-windows-details:
      runs-on: windows-latest
      defaults:
        run:
          shell: pwsh
      steps: 
      -  name: Display working directory and LOF in Windows
         run: |
           Get-Location
           dir
           echo $env:GITHUB_SHA             
           echo $env:GITHUB_REPOSITORY
           echo $env:GITHUB_WORKSPACE
      -  name:  Python shell
         shell: python    
         run: |
           import platform
           print(platform.processor())  
